version: '3.9'

services:
  myspringbootapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - C:\temp\data\db:/data/db
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - C:\temp\data\db:/data/db